### DISCUSSION TITLE
HTTP api on Windows

### DISCUSSION THREAD

**Discussion by liselotte111** [mrene/minidsp-rs#180] [Q&A]
I'm trying to use the http API on Windows (to connect it to Home Assistant). Could someone point me in the right direction how to expose it to the network? All documentation mentions debian (or other unix system).

**Comment by mrene** [comment]
The way you would start the http api on windows is by using `-c config.toml` command line option (with minidspd.exe) and using a [configuration file like this one](https://minidsp-rs.pages.dev/daemon/#configuration)

Change the bind address to `0.0.0.0` as indicated in the comments and it'll be exposed to the network.

**Reply by liselotte111** [reply]
Thank you! Let's see if I can get it to work :)

**Reply by liselotte111** [reply]
Found argument '-c' which wasn't expected, or isn't valid in this context

**Comment by jprouty** [comment]
@liselotte111, I'm curious if you completed your home assistant integration and if it's available for sharing. Cheers!

**Reply by liselotte111** [reply]
Hi! I did get it to work but I used a rpi zero running nodered. If you're interested I could share it. Let me know

**Reply by jprouty** [reply]
If it's not too much trouble I wouldn't mind referencing it. I'll likely write my own HA integration.

**Reply by jprouty** [reply]
Here's my integration: https://github.com/jprouty/hass-minidsp-rs

**Reply by liselotte111** [reply]
I'm sorry I totally forgot. Probably too late now, but anyway. I'm using running nodered on a rpi (to which the minidsp is connected).  Nodered communicates via mqtt to home assistant. 

Some background to the nodes. I've modified my SHD Studio to have trigger ports in (to detect if the tv is on, using a 5v signal from an usb port) and out (to turn on/off the amplifiers). It also automatically switches input (lan and toslink) and changes the volume accordingly. 

I've attached my nodered flow:
[minidsp_nodered.json](https://github.com/user-attachments/files/16680771/minidsp_nodered.json)

![image](https://github.com/user-attachments/assets/8585384d-23bf-44d7-9bbb-c5d5151a1cd3)


And in my HA config:
```
template:
  - sensor:       
    - name: "dspGain"
      state: "{{state_attr('sensor.ddrc24', 'volume') }}"  
    - name: "shdGain"
      state: "{{state_attr('sensor.shd', 'volume') }}"       
  - binary_sensor:
      - name: "dspUSB"
        state: "{{ is_state_attr('sensor.ddrc24', 'source', 'Usb') }}"
      - name: "dspToslink"
        state: "{{ is_state_attr('sensor.ddrc24', 'source', 'Toslink') }}"      
      - name: "dspAnalog"
        state: "{{ is_state_attr('sensor.ddrc24', 'source', 'Analog') }}"   
      - name: "dspMute"
        state: "{{state_attr('sensor.ddrc24', 'mute') }}"        
      - name: "dspDirac"
        state: "{{state_attr('sensor.ddrc24', 'dirac') }}"      
      - name: "shdUSB"
        state: "{{ is_state_attr('sensor.shd', 'source', 'Usb') }}"
      - name: "shdToslink"
        state: "{{ is_state_attr('sensor.shd', 'source', 'Toslink') }}"      
      - name: "shdLan"
        state: "{{ is_state_attr('sensor.shd', 'source', 'Lan') }}"   
      - name: "shdMute"
        state: "{{state_attr('sensor.shd', 'mute') }}"        
      - name: "shdDirac"
        state: "{{state_attr('sensor.shd', 'dirac') }}"           
        
     
mqtt:
  sensor:
    - name: "ddrc24"
      state_topic: "minidsp/status"
      value_template: "{{ value_json.master.volume }}"
      json_attributes_topic: "minidsp/status/attributes"
      json_attributes_template: "{{ value_json.master | tojson}}"
    - name: "shd"
      state_topic: "shd/status"
      value_template: "{{ value_json.master.volume }}"
      json_attributes_topic: "shd/status/attributes"
      json_attributes_template: "{{ value_json.master | tojson}}"      
```

In Lovelace

![image](https://github.com/user-attachments/assets/48b9ea30-9e2a-4109-b354-32e17aaea230)

```

type: vertical-stack
cards:
  - type: horizontal-stack
    cards:
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: perform-action
          perform_action: mqtt.publish
        icon: mdi:television
        entity: binary_sensor.shdtoslink
        name: TV
      - type: button
        tap_action:
          action: call-service
          service: mqtt.publish
          target: {}
          data:
            topic: shd/set
            payload: source usb
        icon: mdi:usb-port
        entity: binary_sensor.shdusb
        name: USB
      - type: button
        tap_action:
          action: call-service
          service: mqtt.publish
          target: {}
          data:
            topic: shd/set
            payload: source lan
        icon: mdi:lan
        entity: binary_sensor.shdlan
        name: ' LAN'
      - show_name: true
        show_icon: true
        type: button
        icon: mdi:music-note-plus
        name: ' Dirac'
        entity: binary_sensor.shddirac
        tap_action:
          action: call-service
          service: mqtt.publish
          data:
            payload_template: >-
              {{ 'dirac false' if is_state('binary_sensor.shddirac', 'on') else
              'dirac true' }}
            topic: shd/set
          target: {}
  - type: horizontal-stack
    cards:
      - type: button
        tap_action:
          action: call-service
          service: mqtt.publish
          target: {}
          data:
            topic: shd/set
            payload: gain -r 1
        icon: mdi:volume-high
      - type: button
        tap_action:
          action: call-service
          service: mqtt.publish
          target: {}
          data:
            topic: shd/set
            payload: gain -r -- -1
        icon: mdi:volume-medium
      - show_name: true
        show_icon: true
        type: button
        icon: mdi:volume-off
        entity: binary_sensor.shdmute
        tap_action:
          action: call-service
          service: mqtt.publish
          data:
            payload_template: >-
              {{ 'mute false' if is_state('binary_sensor.shdmute', 'on') else
              'mute true' }}
            topic: shd/set
          target: {}
      - type: entity
        entity: sensor.shdgain
        name: ' dB'
        icon: ' '

```
