### ISSUE TITLE
Unable to connect more than 1 factory software plugins to minidsp-rs daemon on rpi

### ISSUE THREAD

**Issue by sirjaymz** [mrene/minidsp-rs#662]
if I disconnect and only connect 1 at a time, then it works as expected, with being able to set back defaults or make updates as needed.. But as soon as I try to connect more than 1 instance to the minidsp-rs daemon on the rpi, the 2nd and 3rd instanaces, both ran on different windows machines, lock up.

 If I use the original software stack , I can only connect to one of the units at a time.  Using 1 machine , I can connect to the first one , doesn’t matter which one , without issue. As soon as I try to use another machine , with original software stack, and try to connect to the second unit , or third unit , the software stack hangs, or times out.  Only way to recover is task manager to terminate connections and use only a single unit. The pi is running latest version 0.1.9 minidsp-rs. 

```toml
[[tcp_server]]
bind_address = "192.168.192.71:5333"
device_serial = 907272
advertise = { ip = "192.168.192.71", name = "Open,Open,Row1,Row2" }

[[tcp_server]]
bind_address = "192.168.192.72:5333"
device_serial = 906500
advertise = { ip = "192.168.192.72", name = "MiniMarty's" }

[[tcp_server]]
bind_address = "192.168.192.73:5333"
device_serial = 918822
advertise = { ip = "192.168.192.73", name = "18Sealed & PA460's" }
```

rpi 3b 4gb

```shell
pi@mediapi:/etc/minidsp $ curl http://127.0.0.1:5380/devices
[
  {
    "url": "usb:1-1.4%3A1.4?vid=2752&pid=0011",
    "version": {
      "hw_id": 10,
      "fw_major": 1,
      "fw_minor": 50,
      "dsp_version": 100,
      "serial": 906500
    },
    "product_name": "2x4HD"
  },
  {
    "url": "usb:1-1.2%3A1.4?vid=2752&pid=0011",
    "version": {
      "hw_id": 10,
      "fw_major": 1,
      "fw_minor": 50,
      "dsp_version": 100,
      "serial": 907272
    },
    "product_name": "2x4HD"
  },
  {
    "url": "usb:1-1.1%3A1.4?vid=2752&pid=0011",
    "version": {
      "hw_id": 10,
      "fw_major": 1,
      "fw_minor": 50,
      "dsp_version": 100,
      "serial": 918822
    },
    "product_name": "2x4HD"
  },
  {
    "url": "tcp://192.168.192.70:5333?name=Open%2COpen%2CRow1%2CRow2",
    "version": null,
    "product_name": null
  },
  {
    "url": "tcp://192.168.192.70:5333?name=18Sealed%20%26%20PA460%27s",
    "version": null,
    "product_name": null
  },
  {
    "url": "tcp://192.168.192.70:5333?name=MiniMarty%27s",
    "version": null,
    "product_name": null
  }
```
